### ISSUE TITLE
Todo: SAMIN

### ISSUE THREAD

**Issue by pkofod** [JuliaNLSolvers/Optim.jl#555]
- [x] introduce trace
- [ ] improve test coverage
- [ ] maybe introduce a convergence flag so there's only one place MultivariateOptimizationResults is returned.
- [ ] maybe pull in the alternative boxed simulated annealing scheme in https://github.com/multidis/SATsallis.jl

**Comment by mcreel** [comment]
Just tried the SAMIN code on master: looks good! Thanks! One comment about the Rosenbrock example: with wide bounds on the parameters and fast cooling, the algorithm "quenches". Practically, the search region is narrowed too quickly, and the actual minimizer is missed. By using SAMIN(rt=0.9) a much more accurate solution will be found. Thanks again for getting this in!

**Comment by mcreel** [comment]
SA has two important parts: the bounds, and the temperature. The algorithm will search in an effective way over given bounds if the temperature is high enough. Currently, the bounds are given, and the code goes through a round of increasing the temperature until the draws are covering the bounds. This is to achieve effective global minimization over the supplied parameter space.

Normally, I would say, users may have prior opinions about the reasonable parameter space, e.g., a parameter might be positive, or in the (0,1) interval. So allowing that to be used seems reasonable.

Also, the algorithm follows the referenced articles, which explain the theory. Altering the method without taking into account the theory could lead to unexpected results. The main goal of SA is global minimization. Setting bounds automatically could very well result in too narrow bounds, which could leve the actual global minimum outside of the search region.

**Comment by iwelch** [comment]
all makes sense---global searchers should reasonably specify bounds.  it is almost silly use with out.

except that it makes the API inconsistent.  does Particle Swarm not have the same issue?

**Comment by pkofod** [comment]
> Particle Swarm not have the same issue?

particle swarm has an old style specification of lower and upper bounds, and it'll be changed soon, but yes the issue is the same

**Comment by iwelch** [comment]
will SAMIN use the Fminbox syntax, too?
