### ISSUE TITLE
Roadmap-ish stuff

### ISSUE THREAD

**Issue by pkofod** [JuliaNLSolvers/Optim.jl#662]
**Documentation**
- [ ] General QA on the contents
- [ ] Identify weak pages
- [ ] Add references

**Solvers** (up for grabs if the person is willing to "maintain")
- [ ] Subplex #272 
- [ ] Parallel NelderMead #268

**Cleanup**
- [ ] the new maximize helper function
- [ ] Fminbox api (still corner cases!)

Stolen from #326

**Comment by timholy** [comment]
I haven't followed Optim in ages (will dip back in occasionally when I need it for a new project or update an old one), so here's an incredibly naive "roadmap" question: what's the state of structured Hessians? E.g., for some problems it would be great to be able to provide the hessian in `SparseMatrixCSC` or `Woodbury` form. If this is not implemented, I'd be curious to know whether it's a valid roadmap item, since it's an area where the C libraries are limited (e.g., Ipopt doesn't support Woodbury at all) and Julia's composability could really shine and deliver some huge performance advantages.

**Comment by pkofod** [comment]
You should be able to do that. Can you show me a simple example?

**Comment by timholy** [comment]
Haven't tried. I just remember the days when it wasn't possible, and a brief search of both the README and the documentation failed to turn up any hits for "sparse." That's the extent of my investigations (sorry, this was me being lazy).

**Comment by pkofod** [comment]
I’ll try to give an example. Just gotta find a problem with a Woodbury matrix hessian :)

**Comment by pkofod** [comment]
I havn't found anything yet, but googling gives me Hessian Avenue in Woodbury, NJ. Not quite what I was looking for, but ... :)

**Comment by timholy** [comment]
Try
```julia
f(x) = sum(abs2, x)^2 + (a'*x)^2
```
for vector `a` and `x`.

**Comment by bhalonen** [comment]
Anyone make any progress on paralell NelderMead? @pkofod

**Comment by pkofod** [comment]
Not really. Do you have a specific use-case for it? I don't think it's too hard to implement, I just happen to have gradients available for most of the stuff I do, so I rarely use "vanilla" nelder mead.

**Comment by bhalonen** [comment]
I am considering it as an option. I am working on a personal project of building a functional digital image correlation package, [DIC.jl](https://github.com/bhalonen/DIC.jl) as a science project and a demonstration of capabilities for contracting Julia work. It works with Nelder Mead, but it takes about 45 seconds to finish for my demo case. I spent a few hours this morning building a gradient function. I made at least some progress on that, so I am going to pursue that for the short term.
